version: '3.7'
services:
  db:
    image: mariadb:10.7
    environment:
      - MARIADB_DATABASE=time_entries
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "3306:3306"  